# placeholder_api_app.py
# api/app.py
#
# FastAPI Application Factory
#
# Creates and configures the FastAPI app instance.
# Responsibilities:
#   - Mount all routers (chat, health)
#   - Configure CORS middleware (restrict origins in production!)
#   - Load environment variables
#   - Provide startup / shutdown lifecycle hooks if needed
#
# Run with:
#   uvicorn api.app:app --reload --port 8000
#
# Interactive API docs (auto-generated by FastAPI):
#   http://localhost:8000/docs      ← Swagger UI
#   http://localhost:8000/redoc     ← ReDoc
#
# TODO: add CORSMiddleware and restrict allow_origins in production
# TODO: mount api.routes.chat router at prefix "/chat"
# TODO: mount api.routes.health router at prefix "/health"
# TODO: add startup event to validate Supabase connection

from fastapi import FastAPI

# PLACEHOLDER — import routers once implemented
# from api.routes.chat import router as chat_router
# from api.routes.health import router as health_router

app = FastAPI(
    title="XMUM Campus Chatbot API",
    description="REST API for the XMUM Campus Knowledge Chatbot. "
                "Consumed by React / Next.js frontends.",
    version="0.1.0",
)

# PLACEHOLDER — CORS middleware (configure properly before production)
# from fastapi.middleware.cors import CORSMiddleware
# app.add_middleware(
#     CORSMiddleware,
#     allow_origins=["http://localhost:3000"],  # replace with your frontend URL
#     allow_credentials=True,
#     allow_methods=["*"],
#     allow_headers=["*"],
# )

# PLACEHOLDER — include routers
# app.include_router(chat_router, prefix="/chat", tags=["Chat"])
# app.include_router(health_router, prefix="/health", tags=["Health"])


@app.get("/")
def root():
    """Root endpoint — returns a welcome message."""
    return {"message": "XMUM Campus Chatbot API is running. Visit /docs for API reference."}
